"""v2_initial_schema

Revision ID: e85bf13dd867
Revises: 
Create Date: 2026-07-03 16:47:49.872464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85bf13dd867'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='永久业务标识 UUID'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='展示名/昵称'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active | disabled | deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户 ID'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='password | phone | wechat'),
    sa.Column('identifier', sa.String(length=128), nullable=False, comment='账号名 | 手机号 | openid'),
    sa.Column('secret', sa.String(length=256), nullable=True, comment='密码 bcrypt hash；OAuth 可为空'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='绑定时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'identifier', name='uq_credential_type_identifier')
    )
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_table('safety_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='关联会话 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户 ID'),
    sa.Column('level', sa.Integer(), nullable=False, comment='0 通过 / 1 记录 / 2 紧急'),
    sa.Column('blocked', sa.Boolean(), nullable=False, comment='是否触发安全短路'),
    sa.Column('matched_terms', sa.Text(), nullable=True, comment='命中敏感词（AES 加密后明文存此）'),
    sa.Column('reviewed', sa.Boolean(), nullable=False, comment='是否人审'),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_flags_session_id'), 'safety_flags', ['session_id'], unique=False)
    op.create_index(op.f('ix_safety_flags_user_id'), 'safety_flags', ['user_id'], unique=False)
    op.create_table('scale_screenings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='关联会话 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户 ID'),
    sa.Column('scale_type', sa.String(length=32), nullable=False, comment='PHQ-9 | GAD-7 | ...'),
    sa.Column('state', sa.String(length=16), nullable=False, comment='in_progress | completed | abandoned'),
    sa.Column('responses', sa.Text(), nullable=True, comment='逐题作答 JSON'),
    sa.Column('scores', sa.Text(), nullable=True, comment='各维度得分 JSON'),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='锚点评级 JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scale_screenings_session_id'), 'scale_screenings', ['session_id'], unique=False)
    op.create_index(op.f('ix_scale_screenings_user_id'), 'scale_screenings', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID（完整 UUID）'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户 ID'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='消息数量'),
    sa.Column('key_topics', sa.Text(), nullable=True, comment='关键话题 JSON'),
    sa.Column('scale_history', sa.Text(), nullable=True, comment='量表历史 JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('last_active', sa.DateTime(), nullable=True, comment='最后活跃'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('emotion_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户 ID（跨会话趋势查询）'),
    sa.Column('primary_emotion', sa.String(length=32), nullable=False, comment='主情绪'),
    sa.Column('intensity', sa.Float(), nullable=False, comment='情绪强度 0~1'),
    sa.Column('risk', sa.Float(), nullable=True, comment='风险值 0~1'),
    sa.Column('triggers', sa.Text(), nullable=True, comment='触发因素 JSON'),
    sa.Column('context', sa.Text(), nullable=True, comment='情境上下文（存储层为 AES 密文）'),
    sa.Column('intent', sa.String(length=32), nullable=True, comment='intent 标签'),
    sa.Column('modality_notes', sa.Text(), nullable=True, comment='模态附加信息 JSON'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_records_session_id'), 'emotion_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_emotion_records_user_id'), 'emotion_records', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='user | assistant | system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容（存储层为 AES 密文）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema — 按依赖逆序删表（MySQL drop_table 自动清理 FK 和索引）。"""
    op.drop_table('messages')
    op.drop_table('emotion_records')
    op.drop_table('sessions')
    op.drop_table('scale_screenings')
    op.drop_table('safety_flags')
    op.drop_table('credentials')
    op.drop_table('users')
